\c APP_DB

CREATE DOMAIN FINANCIAL AS NUMERIC(20,4);

CREATE TABLE IF NOT EXISTS ASSET_TYPE (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE
);
INSERT INTO ASSET_TYPE (code, name) VALUES
('STOCK', 'Stock'),
('BOND', 'Bond'),
('ETF', 'ETF'),
('REAL_ESTATE', 'Real Estate'),
('COMMODITY', 'Commodity'),
('FUND', 'Fund'),
('CASH', 'Cash'),
('OTHER', 'Other');

CREATE TABLE IF NOT EXISTS LOG (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type VARCHAR(10) NOT NULL,
    message TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TAX_RATE (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    rate NUMERIC(5,2) NOT NULL DEFAULT 0.00
);
INSERT INTO TAX_RATE (name, rate) VALUES
('Standard', 19.00),
('Zero', 0.00);

CREATE TABLE IF NOT EXISTS PORTFOLIO (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    taxable BOOLEAN NOT NULL DEFAULT TRUE,
    tax_rate_id INTEGER NOT NULL,
    constraint fk_tax_rate FOREIGN KEY (tax_rate_id) REFERENCES TAX_RATE(id) ON DELETE CASCADE
);

INSERT INTO PORTFOLIO (name, taxable, tax_rate_id) VALUES
('General', TRUE, 1),
('IKE', FALSE, 2),
('IKZE', FALSE, 2),
('Brokerage', TRUE, 1),
('PPK', TRUE, 1);

CREATE TABLE IF NOT EXISTS ACCOUNT_TYPE (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    currency VARCHAR(3) NOT NULL
);

INSERT INTO ACCOUNT_TYPE (name, currency) VALUES
('Cash', 'PLN'),
('Cash', 'USD'),
('Cash', 'EUR'),
('Bond', 'PLN'),
('Stock', 'PLN'),
('ETF', 'PLN'),
('Real Estate', 'PLN'),
('Commodity', 'PLN'),
('Counterparty', 'PLN'),
('Dividend', 'PLN'),
('Fee', 'PLN'),
('Interest', 'PLN'),
('Tax', 'PLN'),
('Tax Return', 'PLN'),
('P&L', 'PLN'),
('P&L', 'EUR'),
('P&L', 'USD')
;

CREATE TABLE IF NOT EXISTS ACCOUNT (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL,
    portfolio_id INTEGER NOT NULL,
    constraint fk_account_type FOREIGN KEY (account_id) REFERENCES ACCOUNT_TYPE(id) ON DELETE CASCADE,
    constraint fk_portfolio FOREIGN KEY (portfolio_id) REFERENCES PORTFOLIO(id) ON DELETE CASCADE
);

INSERT INTO ACCOUNT (account_id, portfolio_id)
SELECT a.id as account_id, p.id as portfolio_id FROM ACCOUNT_TYPE a CROSS JOIN PORTFOLIO p
WHERE a.name != 'Tax' and p.taxable = FALSE
UNION ALL
SELECT a.id as account_id, p.id as portfolio_id FROM ACCOUNT_TYPE a CROSS JOIN PORTFOLIO p
WHERE a.name != 'Tax Return' and p.taxable = TRUE;

CREATE TABLE IF NOT EXISTS STG_ASSET_DATA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    isin VARCHAR(20),
    ticker VARCHAR(20),
    asset_type_code VARCHAR(20) NOT NULL,
    date DATE,
    price FINANCIAL,
    currency VARCHAR(3) NOT NULL,
    constraint unique_stg_asset UNIQUE (name, isin, date, price, currency)
);

CREATE TABLE IF NOT EXISTS STG_TRANSACTION_DATA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date DATE NOT NULL,
 --   asset_isin VARCHAR(20),
    asset_name VARCHAR(100) NOT NULL,
    ticker VARCHAR(20),
    transaction_type_code VARCHAR(3) NOT NULL,
    quantity INTEGER,
    currency VARCHAR(3) NOT NULL,
    price FINANCIAL NOT NULL,
    total_amount FINANCIAL,
    fee FINANCIAL,
    total_with_fee FINANCIAL,
    tax_amount FINANCIAL,
    portfolio_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS TRANSACTION_TYPE (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(3) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO TRANSACTION_TYPE (code, name) VALUES
('BUY', 'Buy'),
('SEL', 'Sell'),
('DIV', 'Dividend'),
('INT', 'Interest'),
('FEE', 'Fee'),
('TAX', 'Tax'),
('TRT', 'Tax Return'),
('TRF', 'Transfer');


CREATE TABLE IF NOT EXISTS ASSET (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    isin VARCHAR(20),
    ticker VARCHAR(20),
    asset_type_id INTEGER NOT NULL,
    currency VARCHAR(3),
    constraint fk_asset_type FOREIGN KEY (asset_type_id) REFERENCES ASSET_TYPE(id) ON DELETE CASCADE,
    constraint unique_asset UNIQUE (name, isin, ticker)
);

INSERT INTO ASSET (name, asset_type_id, currency)
VALUES
('Cash', 7, 'PLN'),
('Cash', 7, 'EUR'),
('Cash', 7, 'USD')
;

CREATE TABLE IF NOT EXISTS ASSET_VALUATION (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id INTEGER NOT NULL,
    date DATE NOT NULL,
    currency VARCHAR(3) NOT NULL,
    price FINANCIAL NOT NULL,
    constraint fk_asset FOREIGN KEY (asset_id) REFERENCES ASSET(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EXCHANGE_RATE (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_currency VARCHAR(3) NOT NULL,
    to_currency VARCHAR(3) NOT NULL,
    date DATE NOT NULL,
    rate FINANCIAL NOT NULL,
    constraint unique_exchange_rate UNIQUE (from_currency, to_currency, date)
);

CREATE TABLE IF NOT EXISTS TRANSACTION (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    description TEXT NOT NULL,
    transaction_type_id INTEGER NOT NULL,
    asset_id INTEGER NOT NULL,
    quantity INTEGER,
    currency VARCHAR(3) NOT NULL,
    price FINANCIAL NOT NULL,
    total_amount FINANCIAL,
    fee FINANCIAL DEFAULT 0,
    tax_amount FINANCIAL DEFAULT 0,
    portfolio_id INTEGER NOT NULL,
    transaction_result FINANCIAL,
    constraint fk_portfolio FOREIGN KEY (portfolio_id) REFERENCES PORTFOLIO(id) ON DELETE CASCADE,
    constraint fk_asset FOREIGN KEY (asset_id) REFERENCES ASSET(id) ON DELETE CASCADE,
    constraint fk_transaction_type FOREIGN KEY (transaction_type_id) REFERENCES TRANSACTION_TYPE(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PORTFOLIO_VALUATION (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id INTEGER NOT NULL,
    date DATE NOT NULL,
    currency VARCHAR(3) NOT NULL,
    total_value FINANCIAL NOT NULL,
	total_cost FINANCIAL NOT NULL,
    constraint fk_portfolio FOREIGN KEY (portfolio_id) REFERENCES PORTFOLIO(id) ON DELETE CASCADE,
    unique (portfolio_id, date)
);

CREATE TABLE IF NOT EXISTS TRANSACTION_LOT (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id INTEGER NOT NULL,
    asset_id INTEGER NOT NULL,
    transaction_id INTEGER NOT NULL,
    date DATE NOT NULL,
    currency VARCHAR(3) NOT NULL,
    quantity INTEGER NOT NULL,
    price FINANCIAL,
    cost_base_amount FINANCIAL NOT NULL,
    constraint fk_portfolio FOREIGN KEY (portfolio_id) REFERENCES PORTFOLIO(id) ON DELETE CASCADE,
    constraint fk_asset FOREIGN KEY (asset_id) REFERENCES ASSET(id) ON DELETE CASCADE,
    constraint fk_position FOREIGN KEY (transaction_id) REFERENCES TRANSACTION(id) ON DELETE CASCADE
);

CREATE OR REPLACE VIEW POSITION AS
SELECT 	pos.*, 
		div.total_dividend, 
		div.dividend_tax, 
		interest.total_interest, 
		interest.interest_tax,
		COALESCE(pos.realized_gain, 0) + COALESCE(div.total_dividend, 0) + COALESCE(interest.total_interest, 0) AS total_gain,
		COALESCE(pos.total_tax, 0) + COALESCE(div.dividend_tax, 0) + COALESCE(interest.interest_tax, 0) AS all_tax,
		COALESCE(pos.realized_gain, 0) + COALESCE(div.total_dividend, 0) + 
		COALESCE(interest.total_interest, 0) + COALESCE(pos.current_unrealized_gain, 0) AS total_gained_value
FROM
(SELECT
        t.asset_id,
        t.portfolio_id,
        SUM(tl.quantity) AS quantity,
        t.currency,
		ROUND(SUM(tl.cost_base_amount)/SUM(tl.quantity),4) AS avg_buy_price,
        SUM(tl.cost_base_amount) * COALESCE(MAX(er.rate), 1) AS total_cost,
        SUM(t.fee) AS total_fee,
        SUM(t.tax_amount) AS total_tax,
		COALESCE(MAX(av.date), MAX(er.date)) AS valuation_date,
		MAX(av.price) AS current_price,
		MAX(av.price) * SUM(tl.quantity) * COALESCE(MAX(er.rate), 1) AS current_holding_value,
		(MAX(av.price) * SUM(tl.quantity) * COALESCE(MAX(er.rate), 1)) - (SUM(tl.cost_base_amount) * COALESCE(MAX(er.rate), 1)) AS current_unrealized_gain,
		SUM(t.transaction_result) as realized_gain
    FROM TRANSACTION t
	LEFT JOIN TRANSACTION_LOT tl
		ON tl.transaction_id = t.id
	LEFT JOIN (SELECT asset_id, 
                price, 
                date,
				currency
                FROM (
                    (SELECT RANK() OVER (PARTITION BY asset_id ORDER BY date DESC) AS RNK,
                            asset_id, 
                            price, 
                            date,
                            currency
                     FROM ASSET_VALUATION))
                WHERE RNK = 1 ) av
		ON av.asset_id = t.asset_id
        AND av.currency = t.currency
	LEFT JOIN (SELECT from_currency, to_currency, date, rate FROM
               (SELECT RANK() OVER (PARTITION BY from_currency ORDER BY date DESC) AS RNK,
               from_currency, 
               to_currency, 
               date, 
               rate FROM EXCHANGE_RATE)
               WHERE RNK = 1) er
        ON er.from_currency = t.currency
        AND er.to_currency = 'PLN'
	WHERE t.transaction_type_id IN (SELECT id FROM TRANSACTION_TYPE WHERE code IN ('BUY', 'SEL'))
    GROUP BY 
        t.asset_id,
        t.portfolio_id,
        t.currency
		) pos
	LEFT JOIN (SELECT SUM(price) AS total_dividend,
					  asset_id,
					  portfolio_id,
					  currency,
					  SUM(tax_amount) AS dividend_tax
			   FROM TRANSACTION
			   WHERE transaction_type_id = (SELECT id FROM TRANSACTION_TYPE WHERE code = 'DIV')
			   GROUP BY 
			        asset_id,
					portfolio_id,
					currency) div
		ON div.asset_id = pos.asset_id
		AND div.portfolio_id = pos.portfolio_id
		AND div.currency = pos.currency
	LEFT JOIN (SELECT SUM(price) AS total_interest,
					  asset_id,
					  portfolio_id,
					  currency,
					  SUM(tax_amount) AS interest_tax
			   FROM TRANSACTION
			   WHERE transaction_type_id = (SELECT id FROM TRANSACTION_TYPE WHERE code = 'INT')
			   GROUP BY 
			        asset_id,
					portfolio_id,
					currency) interest
		ON interest.asset_id = pos.asset_id
		AND interest.portfolio_id = pos.portfolio_id
		AND interest.currency = pos.currency
		;

CREATE OR REPLACE VIEW PORTFOLIO_SUMMARY AS 
SELECT *
FROM POSITION
WHERE quantity > 0;