\c APP_DB

CREATE TABLE IF NOT EXISTS ASSET_TYPES (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE
);
INSERT INTO ASSET_TYPES (code, name) VALUES
('STOCK', 'Stock'),
('BOND', 'Bond'),
('ETF', 'ETF'),
('REAL_ESTATE', 'Real Estate'),
('COMMODITY', 'Commodity'),
('FUND', 'Fund'),
('OTHER', 'Other');

CREATE TABLE IF NOT EXISTS LOG (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type VARCHAR(10) NOT NULL,
    message TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TAX_RATES (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    rate MONEY NOT NULL DEFAULT 0.00
);
INSERT INTO TAX_RATES (name, rate) VALUES
('Standard', 19.00),
('Zero', 0.00);

CREATE TABLE IF NOT EXISTS PORTFOLIOS (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    taxable BOOLEAN NOT NULL DEFAULT TRUE,
    tax_rate_id INTEGER NOT NULL,
    constraint fk_tax_rate FOREIGN KEY (tax_rate_id) REFERENCES TAX_RATES(id)
);

INSERT INTO PORTFOLIOS (name, taxable, tax_rate_id) VALUES
('General', TRUE, 1),
('IKE', FALSE, 2),
('IKZE', FALSE, 2),
('Brokerage', TRUE, 1),
('PPK', TRUE, 1);

CREATE TABLE IF NOT EXISTS ACCOUNT_TYPES (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    currency VARCHAR(3) NOT NULL
);

INSERT INTO ACCOUNT_TYPES (name, currency) VALUES
('Cash', 'PLN'),
('Cash', 'USD'),
('Cash', 'EUR'),
('Bond', 'PLN'),
('Stock', 'PLN'),
('ETF', 'PLN'),
('Real Estate', 'PLN'),
('Commodity', 'PLN'),
('Counterparty', 'PLN'),
('Dividend', 'PLN'),
('Fee', 'PLN'),
('Interest', 'PLN'),
('Tax', 'PLN'),
('Tax Return', 'PLN');

CREATE TABLE IF NOT EXISTS ACCOUNTS (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL,
    portfolio_id INTEGER NOT NULL,
    constraint fk_account_type FOREIGN KEY (account_id) REFERENCES ACCOUNT_TYPES(id),
    constraint fk_portfolio FOREIGN KEY (portfolio_id) REFERENCES PORTFOLIOS(id)
);

INSERT INTO ACCOUNTS (account_id, portfolio_id)
SELECT a.id as account_id, p.id as portfolio_id FROM ACCOUNT_TYPES a CROSS JOIN PORTFOLIOS p
WHERE a.name != 'Tax' and p.taxable = FALSE
UNION ALL
SELECT a.id as account_id, p.id as portfolio_id FROM ACCOUNT_TYPES a CROSS JOIN PORTFOLIOS p
WHERE a.name != 'Tax Return' and p.taxable = TRUE;

CREATE TABLE IF NOT EXISTS STG_ASSET_DATA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    isin VARCHAR(20),
    ticker varchar(20),
    asset_type_code VARCHAR(20) NOT NULL,
    date DATE NOT NULL,
    unit_price MONEY NOT NULL,
    currency VARCHAR(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS STG_TRANSACTION_DATA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 --   asset_isin VARCHAR(20),
    asset_name VARCHAR(100) NOT NULL,
    ticker VARCHAR(20),
    transaction_type_code VARCHAR(3) NOT NULL,
    units INTEGER NOT NULL,
    unit_price MONEY NOT NULL,
    total_amount MONEY NOT NULL,
    currency VARCHAR(3) NOT NULL,
    fee MONEY NOT NULL DEFAULT 0,
    total_with_fee MONEY NOT NULL,
    tax_amount MONEY NOT NULL DEFAULT 0,
    portfolio_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS TRANSACTION_TYPES (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(3) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO TRANSACTION_TYPES (code, name) VALUES
('BUY', 'Buy'),
('SEL', 'Sell'),
('DIV', 'Dividend'),
('INT', 'Interest'),
('FEE', 'Fee'),
('TAX', 'Tax'),
('TRT', 'Tax Return');


CREATE TABLE IF NOT EXISTS ASSETS (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    isin VARCHAR(20),
    ticker VARCHAR(20),
    asset_type_id INTEGER NOT NULL,
    constraint fk_asset_type FOREIGN KEY (asset_type_id) REFERENCES ASSET_TYPES(id),
    constraint unique_asset UNIQUE (name, isin, ticker)
);

CREATE TABLE IF NOT EXISTS ASSET_VALUATIONS (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id INTEGER NOT NULL,
    date DATE NOT NULL,
    unit_price MONEY NOT NULL,
    currency VARCHAR(3) NOT NULL,
    constraint fk_asset FOREIGN KEY (asset_id) REFERENCES ASSETS(id)
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    description TEXT NOT NULL,
    transaction_type_id INTEGER NOT NULL,
    asset_id INTEGER NOT NULL,
    units INTEGER NOT NULL,
    unit_price MONEY NOT NULL,
    total_amount MONEY NOT NULL,
    currency VARCHAR(3) NOT NULL,
    fee MONEY NOT NULL DEFAULT 0,
    tax_amount MONEY NOT NULL DEFAULT 0,
    portfolio_id INTEGER NOT NULL,
    constraint fk_portfolio FOREIGN KEY (portfolio_id) REFERENCES PORTFOLIOS(id),
    constraint fk_asset FOREIGN KEY (asset_id) REFERENCES ASSETS(id),
    constraint fk_transaction_type FOREIGN KEY (transaction_type_id) REFERENCES TRANSACTION_TYPES(id)
);

CREATE TABLE IF NOT EXISTS BOOKINGS (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    transaction_id INTEGER NOT NULL,
    debit_account_id INTEGER NOT NULL,
    credit_account_id INTEGER NOT NULL,
    amount MONEY NOT NULL,
    currency VARCHAR(3) NOT NULL,
    constraint fk_transaction FOREIGN KEY (transaction_id) REFERENCES TRANSACTIONS(id),
    constraint fk_debit_account FOREIGN KEY (debit_account_id) REFERENCES ACCOUNTS(id),
    constraint fk_credit_account FOREIGN KEY (credit_account_id) REFERENCES ACCOUNTS(id)
);

CREATE TABLE IF NOT EXISTS PORTFOLIO_VALUATIONS (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id INTEGER NOT NULL,
    date DATE NOT NULL,
    total_value MONEY NOT NULL,
    currency VARCHAR(3) NOT NULL,
    constraint fk_portfolio FOREIGN KEY (portfolio_id) REFERENCES PORTFOLIOS(id)
);