\c APP_DB

CREATE TABLE IF NOT EXISTS ASSET_TYPE (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE
);
INSERT INTO ASSET_TYPE (code, name) VALUES
('STOCK', 'Stock'),
('BOND', 'Bond'),
('ETF', 'ETF'),
('REAL_ESTATE', 'Real Estate'),
('COMMODITY', 'Commodity'),
('FUND', 'Fund'),
('OTHER', 'Other');

CREATE TABLE IF NOT EXISTS LOG (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type VARCHAR(10) NOT NULL,
    message TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TAX_RATE (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    rate NUMERIC(5,2) NOT NULL DEFAULT 0.00
);
INSERT INTO TAX_RATE (name, rate) VALUES
('Standard', 19.00),
('Zero', 0.00);

CREATE TABLE IF NOT EXISTS PORTFOLIO (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    taxable BOOLEAN NOT NULL DEFAULT TRUE,
    tax_rate_id INTEGER NOT NULL,
    constraint fk_tax_rate FOREIGN KEY (tax_rate_id) REFERENCES TAX_RATE(id)
);

INSERT INTO PORTFOLIO (name, taxable, tax_rate_id) VALUES
('General', TRUE, 1),
('IKE', FALSE, 2),
('IKZE', FALSE, 2),
('Brokerage', TRUE, 1),
('PPK', TRUE, 1);

CREATE TABLE IF NOT EXISTS ACCOUNT_TYPE (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    currency VARCHAR(3) NOT NULL
);

INSERT INTO ACCOUNT_TYPE (name, currency) VALUES
('Cash', 'PLN'),
('Cash', 'USD'),
('Cash', 'EUR'),
('Bond', 'PLN'),
('Stock', 'PLN'),
('ETF', 'PLN'),
('Real Estate', 'PLN'),
('Commodity', 'PLN'),
('Counterparty', 'PLN'),
('Dividend', 'PLN'),
('Fee', 'PLN'),
('Interest', 'PLN'),
('Tax', 'PLN'),
('Tax Return', 'PLN');

CREATE TABLE IF NOT EXISTS ACCOUNT (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL,
    portfolio_id INTEGER NOT NULL,
    constraint fk_account_type FOREIGN KEY (account_id) REFERENCES ACCOUNT_TYPE(id),
    constraint fk_portfolio FOREIGN KEY (portfolio_id) REFERENCES PORTFOLIO(id)
);

INSERT INTO ACCOUNT (account_id, portfolio_id)
SELECT a.id as account_id, p.id as portfolio_id FROM ACCOUNT_TYPE a CROSS JOIN PORTFOLIO p
WHERE a.name != 'Tax' and p.taxable = FALSE
UNION ALL
SELECT a.id as account_id, p.id as portfolio_id FROM ACCOUNT_TYPE a CROSS JOIN PORTFOLIO p
WHERE a.name != 'Tax Return' and p.taxable = TRUE;

CREATE TABLE IF NOT EXISTS STG_ASSET_DATA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    isin VARCHAR(20),
    ticker varchar(20),
    asset_type_code VARCHAR(20) NOT NULL,
    date DATE NOT NULL,
    unit_price NUMERIC(20,4) NOT NULL,
    currency VARCHAR(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS STG_TRANSACTION_DATA (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 --   asset_isin VARCHAR(20),
    asset_name VARCHAR(100) NOT NULL,
    ticker VARCHAR(20),
    transaction_type_code VARCHAR(3) NOT NULL,
    units INTEGER NOT NULL,
    unit_price NUMERIC(20,4) NOT NULL,
    total_amount NUMERIC(20,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    fee NUMERIC(20,2) NOT NULL DEFAULT 0,
    total_with_fee NUMERIC(20,2) NOT NULL,
    tax_amount NUMERIC(20,2) NOT NULL DEFAULT 0,
    portfolio_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS TRANSACTION_TYPE (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(3) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO TRANSACTION_TYPE (code, name) VALUES
('BUY', 'Buy'),
('SEL', 'Sell'),
('DIV', 'Dividend'),
('INT', 'Interest'),
('FEE', 'Fee'),
('TAX', 'Tax'),
('TRT', 'Tax Return');


CREATE TABLE IF NOT EXISTS ASSET (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    isin VARCHAR(20),
    ticker VARCHAR(20),
    asset_type_id INTEGER NOT NULL,
    constraint fk_asset_type FOREIGN KEY (asset_type_id) REFERENCES ASSET_TYPE(id),
    constraint unique_asset UNIQUE (name, isin, ticker)
);

CREATE TABLE IF NOT EXISTS ASSET_VALUATION (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id INTEGER NOT NULL,
    date DATE NOT NULL,
    unit_price NUMERIC(20,4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    constraint fk_asset FOREIGN KEY (asset_id) REFERENCES ASSET(id)
);

CREATE TABLE IF NOT EXISTS TRANSACTION (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    description TEXT NOT NULL,
    transaction_type_id INTEGER NOT NULL,
    asset_id INTEGER NOT NULL,
    units INTEGER NOT NULL,
    unit_price NUMERIC(20,4) NOT NULL,
    total_amount NUMERIC(20,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    fee NUMERIC(20,2) NOT NULL DEFAULT 0,
    tax_amount NUMERIC(20,2) NOT NULL DEFAULT 0,
    portfolio_id INTEGER NOT NULL,
    constraint fk_portfolio FOREIGN KEY (portfolio_id) REFERENCES PORTFOLIO(id),
    constraint fk_asset FOREIGN KEY (asset_id) REFERENCES ASSET(id),
    constraint fk_transaction_type FOREIGN KEY (transaction_type_id) REFERENCES TRANSACTION_TYPE(id)
);

CREATE TABLE IF NOT EXISTS BOOKING (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    transaction_id INTEGER NOT NULL,
    debit_account_id INTEGER NOT NULL,
    credit_account_id INTEGER NOT NULL,
    amount NUMERIC(20,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    constraint fk_transaction FOREIGN KEY (transaction_id) REFERENCES TRANSACTION(id),
    constraint fk_debit_account FOREIGN KEY (debit_account_id) REFERENCES ACCOUNT(id),
    constraint fk_credit_account FOREIGN KEY (credit_account_id) REFERENCES ACCOUNT(id)
);

CREATE TABLE IF NOT EXISTS PORTFOLIO_VALUATION (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id INTEGER NOT NULL,
    date DATE NOT NULL,
    total_value NUMERIC(20,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    constraint fk_portfolio FOREIGN KEY (portfolio_id) REFERENCES PORTFOLIO(id)
);